# generated by fastapi-codegen:
#   filename:  api.yml
#   timestamp: 2025-03-26T13:20:42+00:00

from __future__ import annotations

from typing import Optional, Union

from fastapi import FastAPI
from pydantic import constr

from .models import Receipt, ReceiptsIdPointsGetResponse, ReceiptsProcessPostResponse

app = FastAPI(
    title='Receipt Processor',
    description='A simple receipt processor',
    version='0.1.0',
)


@app.post(
    '/receipts/process',
    response_model=None,
    responses={'200': {'model': ReceiptsProcessPostResponse}},
)
def post_receipts_process(body: Receipt) -> Optional[ReceiptsProcessPostResponse]:
    """
    Submits a receipt for processing.
    """
    pass


@app.get(
    '/receipts/{id}/points',
    response_model=None,
    responses={'200': {'model': ReceiptsIdPointsGetResponse}},
)
def get_receipts_id_points(
    id: constr(pattern=r'^\S+$'),
) -> Optional[ReceiptsIdPointsGetResponse]:
    """
    Returns the points awarded for the receipt.
    """
    pass
